### ISSUE TITLE
Build MOI splash page for MWC

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/plan#234]
We need a simple brochure-style page to highlight Mozilla's mobile efforts for Mobile World Congress (MWC)

### RACI

* Phase: dev / qa / ship
* Owner: @edrushka 
* Decision Maker: @HPaulJohnson
* Consulted: @davidascher @benrito @thisandagain 
* Design Lead: @sabrinang 
* Development Lead: @mmmavis 
* Quality Verifier: @cassiemc 

+ Ali (l10n), @adamlofting (metrics)
Consulted: Ben, David A
 Informed : Mark, Geoffrey, Pete S., Andrew, Laura DeR

### Audience
Audiences:
    1)Tech, mainstream and educational press 

    2)Mobile industry partners who want to work with us  

    3)Donor/NGO partners 

    4)Interested Mozillians

### Success
Mobile industry companies partner with us. People use Webmaker's mobile offerings.

### Vision
Splash page is scoped here: https://studiomofo.etherpad.mozilla.org/MOI-splashpage-kickoff

### Milestones: 
https://github.com/mozilla/webmaker.org/milestones/Create%20MOI%20splash%20page%20for%20MWC

**Comment by OpenMatt** [comment]
* next step: break this down into individual tickets. for design vs. dev.

**Comment by edrushka** [comment]
Design is almost done. Mavis will build it this heartbeat.
Design issue: mozilla/webmaker.org#1167
Build issue: mozilla/webmaker.org#1168
All MOI splash page issues: https://github.com/mozilla/webmaker.org/milestones/Create%20MOI%20splash%20page%20for%20MWC

**Comment by OpenMatt** [comment]
Added @cassiemc as quality verifier -- please update or assign someone else if that's wrong

**Comment by OpenMatt** [comment]
@edrushka we good on this one?

**Comment by edrushka** [comment]
@OpenMatt Mavis will start the build when Sabrina locks the design, likely today.  We're on track.

**Comment by edrushka** [comment]
This build is underway. Shifting this ticket to the Feb 27th milestone, as build will not be complete until the 25th.

**Comment by edrushka** [comment]
The build continues: http://moi-splash.herokuapp.com/

**Comment by davidascher** [comment]
We don't still want the privacy icon there do we?

**Comment by adamlofting** [comment]
> We don't still want the privacy icon there do we?

I think you saw the same thing as me where the email notification didn't have the `/localweb` bit on the URL so it was showing the homepage  :confused:. 

@edrushka has fixed in the comment now to be https://moi-splash.herokuapp.com/localweb :smile:

**Comment by edrushka** [comment]
Update: The build should be finished mid-week. We're waiting on:
1) the video (ready ~Feb 25)
2) partner logos [#1175] (https://github.com/mozilla/webmaker.org/issues/1175)
3) a few more PDFs: Webmaker Mobile Partnership [#1283] (https://github.com/mozilla/webmaker.org/issues/1283); the India research report; the final, comprehensive research report.
- a bit of L10N work still happening [#1205] (https://github.com/mozilla/webmaker.org/issues/1205) and [#1271] (https://github.com/mozilla/webmaker.org/issues/1271)

When these are plugged in, we'll do code review and QA.

**Comment by edrushka** [comment]
Page is live: https://webmaker.org/localweb
